### PR TITLE
Create documentation/misleading

### PR DESCRIPTION
**Pull request by Aksel-Rasmussen**
Fake info is amazing!

### CODE REVIEW

**Comment by Aksel-Rasmussen** [comment]
Sorry, just fixing a few things with the repo, was confusered.

**Comment by sql-sith** [comment]
I am uncertain about adding this one.

**Comment by Aksel-Rasmussen** [comment]
I'll let you think on it.

**Comment by sql-sith** [comment]
Hi Aksel. After thinking about this, I'm not sure that I see this PR as beneficial for the team.

**Comment by Aksel-Rasmussen** [comment]
I find that it increases morale. Could you reconsider?

**Comment by sql-sith** [comment]
> I find that it increases morale. Could you reconsider?

I'm sure it increases _your_ morale. ;) 
But since you've asked so nicely...

**Review by sql-sith — APPROVED** [review]
I capitulate.

**Pull request merged**
